# version: '3.8'
services:
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8085:8085"
    volumes:
      - /usr/src/app/node_modules
  db:
    container_name: Postgres
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=col
